### ISSUE TITLE
Incompatible with sqlite-database-integration plugin

### ISSUE THREAD

**Issue by hawm** [mtoensing/simpletoc#42]
When I try to change the settings, something went wrong. I assume it's because using the [sqlite-database-integration plugin](https://github.com/WordPress/sqlite-database-integration), maybe I should ask in this plugin's place.

```
WordPress database error: [<div style="clear:both">&nbsp;</div> <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;"> <p>MySQL query:</p> <p>UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_absolute_urls_enabled'</p> <p>Queries made or created this session were:</p> <ol> <li>Executing: BEGIN | (no parameters)</li> <li>Executing: UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = :param0 | parameters: simpletoc_absolute_urls_enabled</li> <li>Executing: ROLLBACK | (no parameters)</li> </ol> </div> <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;"> Error occurred at line 3373 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: wp_options.option_value. </div> <p>Backtrace:</p> <pre>#0 /var/www/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message() #1 /var/www/html/wp-includes/class-wpdb.php(2766): WP_SQLite_DB->query('UPDATE `wp_opti...') #2 /var/www/html/wp-includes/option.php(547): wpdb->update('wp_options', Array, Array) #3 /var/www/html/wp-admin/options.php(322): update_option('simpletoc_absol...', NULL) #4 {main}</pre> ] UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_absolute_urls_enabled'

WordPress database error: [<div style="clear:both">&nbsp;</div> <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;"> <p>MySQL query:</p> <p>UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_wrapper_enabled'</p> <p>Queries made or created this session were:</p> <ol> <li>Executing: BEGIN | (no parameters)</li> <li>Executing: UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = :param0 | parameters: simpletoc_wrapper_enabled</li> <li>Executing: ROLLBACK | (no parameters)</li> </ol> </div> <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;"> Error occurred at line 3373 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: wp_options.option_value. </div> <p>Backtrace:</p> <pre>#0 /var/www/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message() #1 /var/www/html/wp-includes/class-wpdb.php(2766): WP_SQLite_DB->query('UPDATE `wp_opti...') #2 /var/www/html/wp-includes/option.php(547): wpdb->update('wp_options', Array, Array) #3 /var/www/html/wp-admin/options.php(322): update_option('simpletoc_wrapp...', NULL) #4 {main}</pre> ] UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_wrapper_enabled'

WordPress database error: [<div style="clear:both">&nbsp;</div> <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;"> <p>MySQL query:</p> <p>UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_accordion_enabled'</p> <p>Queries made or created this session were:</p> <ol> <li>Executing: BEGIN | (no parameters)</li> <li>Executing: UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = :param0 | parameters: simpletoc_accordion_enabled</li> <li>Executing: ROLLBACK | (no parameters)</li> </ol> </div> <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;"> Error occurred at line 3373 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: wp_options.option_value. </div> <p>Backtrace:</p> <pre>#0 /var/www/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message() #1 /var/www/html/wp-includes/class-wpdb.php(2766): WP_SQLite_DB->query('UPDATE `wp_opti...') #2 /var/www/html/wp-includes/option.php(547): wpdb->update('wp_options', Array, Array) #3 /var/www/html/wp-admin/options.php(322): update_option('simpletoc_accor...', NULL) #4 {main}</pre> ] UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_accordion_enabled'

WordPress database error: [<div style="clear:both">&nbsp;</div> <div class="queries" style="clear:both;margin-bottom:2px;border:red dotted thin;"> <p>MySQL query:</p> <p>UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_smooth_enabled'</p> <p>Queries made or created this session were:</p> <ol> <li>Executing: BEGIN | (no parameters)</li> <li>Executing: UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = :param0 | parameters: simpletoc_smooth_enabled</li> <li>Executing: ROLLBACK | (no parameters)</li> </ol> </div> <div style="clear:both;margin-bottom:2px;border:red dotted thin;" class="error_message" style="border-bottom:dotted blue thin;"> Error occurred at line 3373 in Function <code>handle_error</code>. Error message was: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: wp_options.option_value. </div> <p>Backtrace:</p> <pre>#0 /var/www/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php(287): WP_SQLite_Translator->get_error_message() #1 /var/www/html/wp-includes/class-wpdb.php(2766): WP_SQLite_DB->query('UPDATE `wp_opti...') #2 /var/www/html/wp-includes/option.php(547): wpdb->update('wp_options', Array, Array) #3 /var/www/html/wp-admin/options.php(322): update_option('simpletoc_smoot...', NULL) #4 {main}</pre> ] UPDATE `wp_options` SET `option_value` = NULL WHERE `option_name` = 'simpletoc_smooth_enabled'

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php:189) in /var/www/html/wp-includes/pluggable.php on line 1435 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-db.php:189) in /var/www/html/wp-includes/pluggable.php on line 1438
```

**Comment by mtoensing** [comment]
Hi, since I did not use any sql queries directly but rely on the Wordpress functions I don’t think i can help here. The sql lite plug-in should try to fix this.
